apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: team08registry.azurecr.io/consumer-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: consumer-db-secret
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: consumer-db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: consumer-db-secret
                  key: DB_PASSWORD
            - name: KAFKA_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: consumer-kafka-secret
                  key: KAFKA_CONNECTION_STRING
            - name: SPRING_PROFILES_ACTIVE
              value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - port: 80
      targetPort: 8080
